// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package rpc

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4cd65213DecodeGithubComYaleOpenLabOpenxRpc(in *jlexer.Lexer, out *StatusResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Code":
			out.Code = int(in.Int())
		case "Status":
			out.Status = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4cd65213EncodeGithubComYaleOpenLabOpenxRpc(out *jwriter.Writer, in StatusResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Code\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Code))
	}
	{
		const prefix string = ",\"Status\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Status))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StatusResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4cd65213EncodeGithubComYaleOpenLabOpenxRpc(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StatusResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4cd65213EncodeGithubComYaleOpenLabOpenxRpc(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StatusResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4cd65213DecodeGithubComYaleOpenLabOpenxRpc(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StatusResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4cd65213DecodeGithubComYaleOpenLabOpenxRpc(l, v)
}
