// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package opensolar

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar(in *jlexer.Lexer, out *statusResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Code":
			out.Code = int(in.Int())
		case "Status":
			out.Status = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar(out *jwriter.Writer, in statusResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Code\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Code))
	}
	{
		const prefix string = ",\"Status\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Status))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v statusResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v statusResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *statusResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *statusResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar(l, v)
}
func easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar1(in *jlexer.Lexer, out *TermsHelper) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Variable":
			out.Variable = string(in.String())
		case "Value":
			out.Value = string(in.String())
		case "RelevantParty":
			out.RelevantParty = string(in.String())
		case "Note":
			out.Note = string(in.String())
		case "Status":
			out.Status = string(in.String())
		case "SupportDoc":
			out.SupportDoc = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar1(out *jwriter.Writer, in TermsHelper) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Variable\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Variable))
	}
	{
		const prefix string = ",\"Value\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Value))
	}
	{
		const prefix string = ",\"RelevantParty\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.RelevantParty))
	}
	{
		const prefix string = ",\"Note\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Note))
	}
	{
		const prefix string = ",\"Status\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"SupportDoc\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.SupportDoc))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TermsHelper) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TermsHelper) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TermsHelper) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TermsHelper) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar1(l, v)
}
func easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar2(in *jlexer.Lexer, out *SustainabilityHelper) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "CarbonDrawdown":
			out.CarbonDrawdown = string(in.String())
		case "CommunityValue":
			out.CommunityValue = string(in.String())
		case "LCA":
			out.LCA = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar2(out *jwriter.Writer, in SustainabilityHelper) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"CarbonDrawdown\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.CarbonDrawdown))
	}
	{
		const prefix string = ",\"CommunityValue\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.CommunityValue))
	}
	{
		const prefix string = ",\"LCA\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.LCA))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SustainabilityHelper) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SustainabilityHelper) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SustainabilityHelper) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SustainabilityHelper) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar2(l, v)
}
func easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar3(in *jlexer.Lexer, out *SolarProjectArray) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(SolarProjectArray, 0, 1)
			} else {
				*out = SolarProjectArray{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 Project
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar3(out *jwriter.Writer, in SolarProjectArray) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v SolarProjectArray) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SolarProjectArray) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SolarProjectArray) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SolarProjectArray) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar3(l, v)
}
func easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar4(in *jlexer.Lexer, out *ProjectSizeHelper) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "PVSolar":
			out.PVSolar = string(in.String())
		case "Storage":
			out.Storage = string(in.String())
		case "Critical":
			out.Critical = float64(in.Float64())
		case "InverterCapacity":
			out.InverterCapacity = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar4(out *jwriter.Writer, in ProjectSizeHelper) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"PVSolar\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.PVSolar))
	}
	{
		const prefix string = ",\"Storage\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Storage))
	}
	{
		const prefix string = ",\"Critical\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.Critical))
	}
	{
		const prefix string = ",\"InverterCapacity\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.InverterCapacity))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ProjectSizeHelper) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ProjectSizeHelper) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ProjectSizeHelper) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ProjectSizeHelper) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar4(l, v)
}
func easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar5(in *jlexer.Lexer, out *Project) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Index":
			out.Index = int(in.Int())
		case "Name":
			out.Name = string(in.String())
		case "State":
			out.State = string(in.String())
		case "Country":
			out.Country = string(in.String())
		case "TotalValue":
			out.TotalValue = float64(in.Float64())
		case "PanelSize":
			out.PanelSize = string(in.String())
		case "PanelTechnicalDescription":
			out.PanelTechnicalDescription = string(in.String())
		case "Inverter":
			out.Inverter = string(in.String())
		case "ChargeRegulator":
			out.ChargeRegulator = string(in.String())
		case "ControlPanel":
			out.ControlPanel = string(in.String())
		case "CommBox":
			out.CommBox = string(in.String())
		case "ACTransfer":
			out.ACTransfer = string(in.String())
		case "SolarCombiner":
			out.SolarCombiner = string(in.String())
		case "Batteries":
			out.Batteries = string(in.String())
		case "IoTHub":
			out.IoTHub = string(in.String())
		case "Rating":
			out.Rating = string(in.String())
		case "Metadata":
			out.Metadata = string(in.String())
		case "MoneyRaised":
			out.MoneyRaised = float64(in.Float64())
		case "EstimatedAcquisition":
			out.EstimatedAcquisition = int(in.Int())
		case "BalLeft":
			out.BalLeft = float64(in.Float64())
		case "InterestRate":
			out.InterestRate = float64(in.Float64())
		case "Tax":
			out.Tax = string(in.String())
		case "DateInitiated":
			out.DateInitiated = string(in.String())
		case "DateFunded":
			out.DateFunded = string(in.String())
		case "DateLastPaid":
			out.DateLastPaid = int64(in.Int64())
		case "AuctionType":
			out.AuctionType = string(in.String())
		case "InvestmentType":
			out.InvestmentType = string(in.String())
		case "PaybackPeriod":
			out.PaybackPeriod = int(in.Int())
		case "Stage":
			out.Stage = int(in.Int())
		case "InvestorAssetCode":
			out.InvestorAssetCode = string(in.String())
		case "DebtAssetCode":
			out.DebtAssetCode = string(in.String())
		case "PaybackAssetCode":
			out.PaybackAssetCode = string(in.String())
		case "SeedAssetCode":
			out.SeedAssetCode = string(in.String())
		case "SeedInvestmentFactor":
			out.SeedInvestmentFactor = float64(in.Float64())
		case "SeedInvestmentCap":
			out.SeedInvestmentCap = float64(in.Float64())
		case "ProposedInvetmentCap":
			out.ProposedInvetmentCap = float64(in.Float64())
		case "SelfFund":
			out.SelfFund = float64(in.Float64())
		case "EscrowPubkey":
			out.EscrowPubkey = string(in.String())
		case "EscrowLock":
			out.EscrowLock = bool(in.Bool())
		case "SecurityIssuer":
			out.SecurityIssuer = string(in.String())
		case "BrokerDealer":
			out.BrokerDealer = string(in.String())
		case "RecipientIndex":
			out.RecipientIndex = int(in.Int())
		case "OriginatorIndex":
			out.OriginatorIndex = int(in.Int())
		case "GuarantorIndex":
			out.GuarantorIndex = int(in.Int())
		case "ContractorIndex":
			out.ContractorIndex = int(in.Int())
		case "MainDeveloperIndex":
			out.MainDeveloperIndex = int(in.Int())
		case "BlendedCapitalInvestorIndex":
			out.BlendedCapitalInvestorIndex = int(in.Int())
		case "InvestorIndices":
			if in.IsNull() {
				in.Skip()
				out.InvestorIndices = nil
			} else {
				in.Delim('[')
				if out.InvestorIndices == nil {
					if !in.IsDelim(']') {
						out.InvestorIndices = make([]int, 0, 8)
					} else {
						out.InvestorIndices = []int{}
					}
				} else {
					out.InvestorIndices = (out.InvestorIndices)[:0]
				}
				for !in.IsDelim(']') {
					var v4 int
					v4 = int(in.Int())
					out.InvestorIndices = append(out.InvestorIndices, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "SeedInvestorIndices":
			if in.IsNull() {
				in.Skip()
				out.SeedInvestorIndices = nil
			} else {
				in.Delim('[')
				if out.SeedInvestorIndices == nil {
					if !in.IsDelim(']') {
						out.SeedInvestorIndices = make([]int, 0, 8)
					} else {
						out.SeedInvestorIndices = []int{}
					}
				} else {
					out.SeedInvestorIndices = (out.SeedInvestorIndices)[:0]
				}
				for !in.IsDelim(']') {
					var v5 int
					v5 = int(in.Int())
					out.SeedInvestorIndices = append(out.SeedInvestorIndices, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "RecipientIndices":
			if in.IsNull() {
				in.Skip()
				out.RecipientIndices = nil
			} else {
				in.Delim('[')
				if out.RecipientIndices == nil {
					if !in.IsDelim(']') {
						out.RecipientIndices = make([]int, 0, 8)
					} else {
						out.RecipientIndices = []int{}
					}
				} else {
					out.RecipientIndices = (out.RecipientIndices)[:0]
				}
				for !in.IsDelim(']') {
					var v6 int
					v6 = int(in.Int())
					out.RecipientIndices = append(out.RecipientIndices, v6)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "DeveloperIndices":
			if in.IsNull() {
				in.Skip()
				out.DeveloperIndices = nil
			} else {
				in.Delim('[')
				if out.DeveloperIndices == nil {
					if !in.IsDelim(']') {
						out.DeveloperIndices = make([]int, 0, 8)
					} else {
						out.DeveloperIndices = []int{}
					}
				} else {
					out.DeveloperIndices = (out.DeveloperIndices)[:0]
				}
				for !in.IsDelim(']') {
					var v7 int
					v7 = int(in.Int())
					out.DeveloperIndices = append(out.DeveloperIndices, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "ContractorFee":
			out.ContractorFee = float64(in.Float64())
		case "OriginatorFee":
			out.OriginatorFee = float64(in.Float64())
		case "DeveloperFee":
			if in.IsNull() {
				in.Skip()
				out.DeveloperFee = nil
			} else {
				in.Delim('[')
				if out.DeveloperFee == nil {
					if !in.IsDelim(']') {
						out.DeveloperFee = make([]float64, 0, 8)
					} else {
						out.DeveloperFee = []float64{}
					}
				} else {
					out.DeveloperFee = (out.DeveloperFee)[:0]
				}
				for !in.IsDelim(']') {
					var v8 float64
					v8 = float64(in.Float64())
					out.DeveloperFee = append(out.DeveloperFee, v8)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "DebtInvestor1":
			out.DebtInvestor1 = string(in.String())
		case "DebtInvestor2":
			out.DebtInvestor2 = string(in.String())
		case "TaxEquityInvestor":
			out.TaxEquityInvestor = string(in.String())
		case "Lock":
			out.Lock = bool(in.Bool())
		case "LockPwd":
			out.LockPwd = string(in.String())
		case "Votes":
			out.Votes = int(in.Int())
		case "AmountOwed":
			out.AmountOwed = float64(in.Float64())
		case "Reputation":
			out.Reputation = float64(in.Float64())
		case "OwnershipShift":
			out.OwnershipShift = float64(in.Float64())
		case "StageData":
			if in.IsNull() {
				in.Skip()
				out.StageData = nil
			} else {
				in.Delim('[')
				if out.StageData == nil {
					if !in.IsDelim(']') {
						out.StageData = make([]string, 0, 4)
					} else {
						out.StageData = []string{}
					}
				} else {
					out.StageData = (out.StageData)[:0]
				}
				for !in.IsDelim(']') {
					var v9 string
					v9 = string(in.String())
					out.StageData = append(out.StageData, v9)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "StageChecklist":
			if in.IsNull() {
				in.Skip()
				out.StageChecklist = nil
			} else {
				in.Delim('[')
				if out.StageChecklist == nil {
					if !in.IsDelim(']') {
						out.StageChecklist = make([]map[string]bool, 0, 8)
					} else {
						out.StageChecklist = []map[string]bool{}
					}
				} else {
					out.StageChecklist = (out.StageChecklist)[:0]
				}
				for !in.IsDelim(']') {
					var v10 map[string]bool
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('{')
						if !in.IsDelim('}') {
							v10 = make(map[string]bool)
						} else {
							v10 = nil
						}
						for !in.IsDelim('}') {
							key := string(in.String())
							in.WantColon()
							var v11 bool
							v11 = bool(in.Bool())
							(v10)[key] = v11
							in.WantComma()
						}
						in.Delim('}')
					}
					out.StageChecklist = append(out.StageChecklist, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "InvestorMap":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.InvestorMap = make(map[string]float64)
				} else {
					out.InvestorMap = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v12 float64
					v12 = float64(in.Float64())
					(out.InvestorMap)[key] = v12
					in.WantComma()
				}
				in.Delim('}')
			}
		case "WaterfallMap":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.WaterfallMap = make(map[string]float64)
				} else {
					out.WaterfallMap = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v13 float64
					v13 = float64(in.Float64())
					(out.WaterfallMap)[key] = v13
					in.WantComma()
				}
				in.Delim('}')
			}
		case "Terms":
			if in.IsNull() {
				in.Skip()
				out.Terms = nil
			} else {
				in.Delim('[')
				if out.Terms == nil {
					if !in.IsDelim(']') {
						out.Terms = make([]TermsHelper, 0, 1)
					} else {
						out.Terms = []TermsHelper{}
					}
				} else {
					out.Terms = (out.Terms)[:0]
				}
				for !in.IsDelim(']') {
					var v14 TermsHelper
					(v14).UnmarshalEasyJSON(in)
					out.Terms = append(out.Terms, v14)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "ExecutiveSummary":
			(out.ExecutiveSummary).UnmarshalEasyJSON(in)
		case "AutoReloadInterval":
			out.AutoReloadInterval = float64(in.Float64())
		case "ResilienceRating":
			out.ResilienceRating = float64(in.Float64())
		case "ActionsRequired":
			out.ActionsRequired = string(in.String())
		case "Bullets":
			(out.Bullets).UnmarshalEasyJSON(in)
		case "Hashes":
			(out.Hashes).UnmarshalEasyJSON(in)
		case "ContractList":
			if in.IsNull() {
				in.Skip()
				out.ContractList = nil
			} else {
				in.Delim('[')
				if out.ContractList == nil {
					if !in.IsDelim(']') {
						out.ContractList = make([]string, 0, 4)
					} else {
						out.ContractList = []string{}
					}
				} else {
					out.ContractList = (out.ContractList)[:0]
				}
				for !in.IsDelim(']') {
					var v15 string
					v15 = string(in.String())
					out.ContractList = append(out.ContractList, v15)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "Architecture":
			(out.Architecture).UnmarshalEasyJSON(in)
		case "Context":
			out.Context = string(in.String())
		case "SummaryImage":
			out.SummaryImage = string(in.String())
		case "CommunityEngagement":
			if in.IsNull() {
				in.Skip()
				out.CommunityEngagement = nil
			} else {
				in.Delim('[')
				if out.CommunityEngagement == nil {
					if !in.IsDelim(']') {
						out.CommunityEngagement = make([]CommunityEngagementHelper, 0, 1)
					} else {
						out.CommunityEngagement = []CommunityEngagementHelper{}
					}
				} else {
					out.CommunityEngagement = (out.CommunityEngagement)[:0]
				}
				for !in.IsDelim(']') {
					var v16 CommunityEngagementHelper
					(v16).UnmarshalEasyJSON(in)
					out.CommunityEngagement = append(out.CommunityEngagement, v16)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "ExplorePageSummary":
			(out.ExplorePageSummary).UnmarshalEasyJSON(in)
		case "DPIntroImage":
			out.DPIntroImage = string(in.String())
		case "OHeroImage":
			out.OHeroImage = string(in.String())
		case "OImages":
			if in.IsNull() {
				in.Skip()
				out.OImages = nil
			} else {
				in.Delim('[')
				if out.OImages == nil {
					if !in.IsDelim(']') {
						out.OImages = make([]string, 0, 4)
					} else {
						out.OImages = []string{}
					}
				} else {
					out.OImages = (out.OImages)[:0]
				}
				for !in.IsDelim(']') {
					var v17 string
					v17 = string(in.String())
					out.OImages = append(out.OImages, v17)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "OOImages":
			if in.IsNull() {
				in.Skip()
				out.OOImages = nil
			} else {
				in.Delim('[')
				if out.OOImages == nil {
					if !in.IsDelim(']') {
						out.OOImages = make([]string, 0, 4)
					} else {
						out.OOImages = []string{}
					}
				} else {
					out.OOImages = (out.OOImages)[:0]
				}
				for !in.IsDelim(']') {
					var v18 string
					v18 = string(in.String())
					out.OOImages = append(out.OOImages, v18)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "AImages":
			if in.IsNull() {
				in.Skip()
				out.AImages = nil
			} else {
				in.Delim('[')
				if out.AImages == nil {
					if !in.IsDelim(']') {
						out.AImages = make([]string, 0, 4)
					} else {
						out.AImages = []string{}
					}
				} else {
					out.AImages = (out.AImages)[:0]
				}
				for !in.IsDelim(']') {
					var v19 string
					v19 = string(in.String())
					out.AImages = append(out.AImages, v19)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "EImages":
			if in.IsNull() {
				in.Skip()
				out.EImages = nil
			} else {
				in.Delim('[')
				if out.EImages == nil {
					if !in.IsDelim(']') {
						out.EImages = make([]string, 0, 4)
					} else {
						out.EImages = []string{}
					}
				} else {
					out.EImages = (out.EImages)[:0]
				}
				for !in.IsDelim(']') {
					var v20 string
					v20 = string(in.String())
					out.EImages = append(out.EImages, v20)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "CEImages":
			if in.IsNull() {
				in.Skip()
				out.CEImages = nil
			} else {
				in.Delim('[')
				if out.CEImages == nil {
					if !in.IsDelim(']') {
						out.CEImages = make([]string, 0, 4)
					} else {
						out.CEImages = []string{}
					}
				} else {
					out.CEImages = (out.CEImages)[:0]
				}
				for !in.IsDelim(']') {
					var v21 string
					v21 = string(in.String())
					out.CEImages = append(out.CEImages, v21)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "PSImages":
			if in.IsNull() {
				in.Skip()
				out.PSImages = nil
			} else {
				in.Delim('[')
				if out.PSImages == nil {
					if !in.IsDelim(']') {
						out.PSImages = make([]string, 0, 4)
					} else {
						out.PSImages = []string{}
					}
				} else {
					out.PSImages = (out.PSImages)[:0]
				}
				for !in.IsDelim(']') {
					var v22 string
					v22 = string(in.String())
					out.PSImages = append(out.PSImages, v22)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "BNImages":
			if in.IsNull() {
				in.Skip()
				out.BNImages = nil
			} else {
				in.Delim('[')
				if out.BNImages == nil {
					if !in.IsDelim(']') {
						out.BNImages = make([]string, 0, 4)
					} else {
						out.BNImages = []string{}
					}
				} else {
					out.BNImages = (out.BNImages)[:0]
				}
				for !in.IsDelim(']') {
					var v23 string
					v23 = string(in.String())
					out.BNImages = append(out.BNImages, v23)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar5(out *jwriter.Writer, in Project) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Index\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Index))
	}
	{
		const prefix string = ",\"Name\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"State\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.State))
	}
	{
		const prefix string = ",\"Country\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Country))
	}
	{
		const prefix string = ",\"TotalValue\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.TotalValue))
	}
	{
		const prefix string = ",\"PanelSize\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.PanelSize))
	}
	{
		const prefix string = ",\"PanelTechnicalDescription\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.PanelTechnicalDescription))
	}
	{
		const prefix string = ",\"Inverter\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Inverter))
	}
	{
		const prefix string = ",\"ChargeRegulator\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ChargeRegulator))
	}
	{
		const prefix string = ",\"ControlPanel\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ControlPanel))
	}
	{
		const prefix string = ",\"CommBox\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.CommBox))
	}
	{
		const prefix string = ",\"ACTransfer\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ACTransfer))
	}
	{
		const prefix string = ",\"SolarCombiner\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.SolarCombiner))
	}
	{
		const prefix string = ",\"Batteries\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Batteries))
	}
	{
		const prefix string = ",\"IoTHub\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.IoTHub))
	}
	{
		const prefix string = ",\"Rating\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Rating))
	}
	{
		const prefix string = ",\"Metadata\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Metadata))
	}
	{
		const prefix string = ",\"MoneyRaised\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.MoneyRaised))
	}
	{
		const prefix string = ",\"EstimatedAcquisition\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.EstimatedAcquisition))
	}
	{
		const prefix string = ",\"BalLeft\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.BalLeft))
	}
	{
		const prefix string = ",\"InterestRate\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.InterestRate))
	}
	{
		const prefix string = ",\"Tax\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Tax))
	}
	{
		const prefix string = ",\"DateInitiated\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.DateInitiated))
	}
	{
		const prefix string = ",\"DateFunded\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.DateFunded))
	}
	{
		const prefix string = ",\"DateLastPaid\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.DateLastPaid))
	}
	{
		const prefix string = ",\"AuctionType\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.AuctionType))
	}
	{
		const prefix string = ",\"InvestmentType\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.InvestmentType))
	}
	{
		const prefix string = ",\"PaybackPeriod\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.PaybackPeriod))
	}
	{
		const prefix string = ",\"Stage\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Stage))
	}
	{
		const prefix string = ",\"InvestorAssetCode\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.InvestorAssetCode))
	}
	{
		const prefix string = ",\"DebtAssetCode\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.DebtAssetCode))
	}
	{
		const prefix string = ",\"PaybackAssetCode\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.PaybackAssetCode))
	}
	{
		const prefix string = ",\"SeedAssetCode\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.SeedAssetCode))
	}
	{
		const prefix string = ",\"SeedInvestmentFactor\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.SeedInvestmentFactor))
	}
	{
		const prefix string = ",\"SeedInvestmentCap\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.SeedInvestmentCap))
	}
	{
		const prefix string = ",\"ProposedInvetmentCap\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.ProposedInvetmentCap))
	}
	{
		const prefix string = ",\"SelfFund\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.SelfFund))
	}
	{
		const prefix string = ",\"EscrowPubkey\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.EscrowPubkey))
	}
	{
		const prefix string = ",\"EscrowLock\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.EscrowLock))
	}
	{
		const prefix string = ",\"SecurityIssuer\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.SecurityIssuer))
	}
	{
		const prefix string = ",\"BrokerDealer\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.BrokerDealer))
	}
	{
		const prefix string = ",\"RecipientIndex\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.RecipientIndex))
	}
	{
		const prefix string = ",\"OriginatorIndex\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.OriginatorIndex))
	}
	{
		const prefix string = ",\"GuarantorIndex\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.GuarantorIndex))
	}
	{
		const prefix string = ",\"ContractorIndex\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ContractorIndex))
	}
	{
		const prefix string = ",\"MainDeveloperIndex\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.MainDeveloperIndex))
	}
	{
		const prefix string = ",\"BlendedCapitalInvestorIndex\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.BlendedCapitalInvestorIndex))
	}
	{
		const prefix string = ",\"InvestorIndices\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.InvestorIndices == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v24, v25 := range in.InvestorIndices {
				if v24 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v25))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"SeedInvestorIndices\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.SeedInvestorIndices == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v26, v27 := range in.SeedInvestorIndices {
				if v26 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v27))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"RecipientIndices\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.RecipientIndices == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v28, v29 := range in.RecipientIndices {
				if v28 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v29))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"DeveloperIndices\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.DeveloperIndices == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v30, v31 := range in.DeveloperIndices {
				if v30 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v31))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"ContractorFee\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.ContractorFee))
	}
	{
		const prefix string = ",\"OriginatorFee\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.OriginatorFee))
	}
	{
		const prefix string = ",\"DeveloperFee\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.DeveloperFee == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v32, v33 := range in.DeveloperFee {
				if v32 > 0 {
					out.RawByte(',')
				}
				out.Float64(float64(v33))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"DebtInvestor1\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.DebtInvestor1))
	}
	{
		const prefix string = ",\"DebtInvestor2\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.DebtInvestor2))
	}
	{
		const prefix string = ",\"TaxEquityInvestor\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.TaxEquityInvestor))
	}
	{
		const prefix string = ",\"Lock\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.Lock))
	}
	{
		const prefix string = ",\"LockPwd\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.LockPwd))
	}
	{
		const prefix string = ",\"Votes\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Votes))
	}
	{
		const prefix string = ",\"AmountOwed\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.AmountOwed))
	}
	{
		const prefix string = ",\"Reputation\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.Reputation))
	}
	{
		const prefix string = ",\"OwnershipShift\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.OwnershipShift))
	}
	{
		const prefix string = ",\"StageData\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.StageData == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v34, v35 := range in.StageData {
				if v34 > 0 {
					out.RawByte(',')
				}
				out.String(string(v35))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"StageChecklist\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.StageChecklist == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v36, v37 := range in.StageChecklist {
				if v36 > 0 {
					out.RawByte(',')
				}
				if v37 == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
					out.RawString(`null`)
				} else {
					out.RawByte('{')
					v38First := true
					for v38Name, v38Value := range v37 {
						if v38First {
							v38First = false
						} else {
							out.RawByte(',')
						}
						out.String(string(v38Name))
						out.RawByte(':')
						out.Bool(bool(v38Value))
					}
					out.RawByte('}')
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"InvestorMap\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.InvestorMap == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v39First := true
			for v39Name, v39Value := range in.InvestorMap {
				if v39First {
					v39First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v39Name))
				out.RawByte(':')
				out.Float64(float64(v39Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"WaterfallMap\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.WaterfallMap == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v40First := true
			for v40Name, v40Value := range in.WaterfallMap {
				if v40First {
					v40First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v40Name))
				out.RawByte(':')
				out.Float64(float64(v40Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"Terms\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.Terms == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v41, v42 := range in.Terms {
				if v41 > 0 {
					out.RawByte(',')
				}
				(v42).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"ExecutiveSummary\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(in.ExecutiveSummary).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"AutoReloadInterval\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.AutoReloadInterval))
	}
	{
		const prefix string = ",\"ResilienceRating\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.ResilienceRating))
	}
	{
		const prefix string = ",\"ActionsRequired\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ActionsRequired))
	}
	{
		const prefix string = ",\"Bullets\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(in.Bullets).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"Hashes\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(in.Hashes).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"ContractList\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.ContractList == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v43, v44 := range in.ContractList {
				if v43 > 0 {
					out.RawByte(',')
				}
				out.String(string(v44))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"Architecture\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(in.Architecture).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"Context\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Context))
	}
	{
		const prefix string = ",\"SummaryImage\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.SummaryImage))
	}
	{
		const prefix string = ",\"CommunityEngagement\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.CommunityEngagement == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v45, v46 := range in.CommunityEngagement {
				if v45 > 0 {
					out.RawByte(',')
				}
				(v46).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"ExplorePageSummary\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(in.ExplorePageSummary).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"DPIntroImage\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.DPIntroImage))
	}
	{
		const prefix string = ",\"OHeroImage\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.OHeroImage))
	}
	{
		const prefix string = ",\"OImages\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.OImages == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v47, v48 := range in.OImages {
				if v47 > 0 {
					out.RawByte(',')
				}
				out.String(string(v48))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"OOImages\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.OOImages == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v49, v50 := range in.OOImages {
				if v49 > 0 {
					out.RawByte(',')
				}
				out.String(string(v50))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"AImages\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.AImages == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v51, v52 := range in.AImages {
				if v51 > 0 {
					out.RawByte(',')
				}
				out.String(string(v52))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"EImages\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.EImages == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v53, v54 := range in.EImages {
				if v53 > 0 {
					out.RawByte(',')
				}
				out.String(string(v54))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"CEImages\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.CEImages == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v55, v56 := range in.CEImages {
				if v55 > 0 {
					out.RawByte(',')
				}
				out.String(string(v56))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"PSImages\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.PSImages == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v57, v58 := range in.PSImages {
				if v57 > 0 {
					out.RawByte(',')
				}
				out.String(string(v58))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"BNImages\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.BNImages == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v59, v60 := range in.BNImages {
				if v59 > 0 {
					out.RawByte(',')
				}
				out.String(string(v60))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Project) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Project) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Project) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Project) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar5(l, v)
}
func easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar6(in *jlexer.Lexer, out *InvestmentHelper) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Capex":
			out.Capex = string(in.String())
		case "Hardware":
			out.Hardware = float64(in.Float64())
		case "FirstLossEscrow":
			out.FirstLossEscrow = string(in.String())
		case "CertificationCosts":
			out.CertificationCosts = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar6(out *jwriter.Writer, in InvestmentHelper) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Capex\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Capex))
	}
	{
		const prefix string = ",\"Hardware\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.Hardware))
	}
	{
		const prefix string = ",\"FirstLossEscrow\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.FirstLossEscrow))
	}
	{
		const prefix string = ",\"CertificationCosts\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.CertificationCosts))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v InvestmentHelper) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v InvestmentHelper) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *InvestmentHelper) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *InvestmentHelper) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar6(l, v)
}
func easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar7(in *jlexer.Lexer, out *HashHelper) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "LegalProjectOverviewHash":
			out.LegalProjectOverviewHash = string(in.String())
		case "LegalPPAHash":
			out.LegalPPAHash = string(in.String())
		case "LegalRECAgreementHash":
			out.LegalRECAgreementHash = string(in.String())
		case "GuarantorAgreementHash":
			out.GuarantorAgreementHash = string(in.String())
		case "ContractorAgreementHash":
			out.ContractorAgreementHash = string(in.String())
		case "StakeholderAgreementHash":
			out.StakeholderAgreementHash = string(in.String())
		case "CommunityEnergyHash":
			out.CommunityEnergyHash = string(in.String())
		case "FinancialReportingHash":
			out.FinancialReportingHash = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar7(out *jwriter.Writer, in HashHelper) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"LegalProjectOverviewHash\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.LegalProjectOverviewHash))
	}
	{
		const prefix string = ",\"LegalPPAHash\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.LegalPPAHash))
	}
	{
		const prefix string = ",\"LegalRECAgreementHash\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.LegalRECAgreementHash))
	}
	{
		const prefix string = ",\"GuarantorAgreementHash\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.GuarantorAgreementHash))
	}
	{
		const prefix string = ",\"ContractorAgreementHash\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ContractorAgreementHash))
	}
	{
		const prefix string = ",\"StakeholderAgreementHash\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.StakeholderAgreementHash))
	}
	{
		const prefix string = ",\"CommunityEnergyHash\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.CommunityEnergyHash))
	}
	{
		const prefix string = ",\"FinancialReportingHash\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.FinancialReportingHash))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v HashHelper) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v HashHelper) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *HashHelper) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *HashHelper) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar7(l, v)
}
func easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar8(in *jlexer.Lexer, out *FinancialHelper) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Return":
			out.Return = float64(in.Float64())
		case "Insurance":
			out.Insurance = string(in.String())
		case "Tariff":
			out.Tariff = string(in.String())
		case "Maturity":
			out.Maturity = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar8(out *jwriter.Writer, in FinancialHelper) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Return\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.Return))
	}
	{
		const prefix string = ",\"Insurance\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Insurance))
	}
	{
		const prefix string = ",\"Tariff\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Tariff))
	}
	{
		const prefix string = ",\"Maturity\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Maturity))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FinancialHelper) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FinancialHelper) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FinancialHelper) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FinancialHelper) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar8(l, v)
}
func easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar9(in *jlexer.Lexer, out *ExplorePageSummaryHelper) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Solar":
			out.Solar = string(in.String())
		case "Storage":
			out.Storage = string(in.String())
		case "Tariff":
			out.Tariff = string(in.String())
		case "Stage":
			out.Stage = int(in.Int())
		case "Return":
			out.Return = string(in.String())
		case "Rating":
			out.Rating = string(in.String())
		case "Tax":
			out.Tax = string(in.String())
		case "ETA":
			out.ETA = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar9(out *jwriter.Writer, in ExplorePageSummaryHelper) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Solar\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Solar))
	}
	{
		const prefix string = ",\"Storage\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Storage))
	}
	{
		const prefix string = ",\"Tariff\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Tariff))
	}
	{
		const prefix string = ",\"Stage\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Stage))
	}
	{
		const prefix string = ",\"Return\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Return))
	}
	{
		const prefix string = ",\"Rating\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Rating))
	}
	{
		const prefix string = ",\"Tax\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Tax))
	}
	{
		const prefix string = ",\"ETA\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ETA))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ExplorePageSummaryHelper) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ExplorePageSummaryHelper) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ExplorePageSummaryHelper) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ExplorePageSummaryHelper) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar9(l, v)
}
func easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar10(in *jlexer.Lexer, out *ExecutiveSummaryHelper) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Investment":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Investment = make(map[string]string)
				} else {
					out.Investment = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v61 string
					v61 = string(in.String())
					(out.Investment)[key] = v61
					in.WantComma()
				}
				in.Delim('}')
			}
		case "Financials":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Financials = make(map[string]string)
				} else {
					out.Financials = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v62 string
					v62 = string(in.String())
					(out.Financials)[key] = v62
					in.WantComma()
				}
				in.Delim('}')
			}
		case "ProjectSize":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.ProjectSize = make(map[string]string)
				} else {
					out.ProjectSize = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v63 string
					v63 = string(in.String())
					(out.ProjectSize)[key] = v63
					in.WantComma()
				}
				in.Delim('}')
			}
		case "SustainabilityMetrics":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.SustainabilityMetrics = make(map[string]string)
				} else {
					out.SustainabilityMetrics = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v64 string
					v64 = string(in.String())
					(out.SustainabilityMetrics)[key] = v64
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar10(out *jwriter.Writer, in ExecutiveSummaryHelper) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Investment\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.Investment == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v65First := true
			for v65Name, v65Value := range in.Investment {
				if v65First {
					v65First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v65Name))
				out.RawByte(':')
				out.String(string(v65Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"Financials\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.Financials == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v66First := true
			for v66Name, v66Value := range in.Financials {
				if v66First {
					v66First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v66Name))
				out.RawByte(':')
				out.String(string(v66Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"ProjectSize\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.ProjectSize == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v67First := true
			for v67Name, v67Value := range in.ProjectSize {
				if v67First {
					v67First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v67Name))
				out.RawByte(':')
				out.String(string(v67Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"SustainabilityMetrics\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.SustainabilityMetrics == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v68First := true
			for v68Name, v68Value := range in.SustainabilityMetrics {
				if v68First {
					v68First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v68Name))
				out.RawByte(':')
				out.String(string(v68Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ExecutiveSummaryHelper) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ExecutiveSummaryHelper) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ExecutiveSummaryHelper) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ExecutiveSummaryHelper) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar10(l, v)
}
func easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar11(in *jlexer.Lexer, out *CommunityEngagementHelper) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Width":
			out.Width = int(in.Int())
		case "Title":
			out.Title = string(in.String())
		case "ImageURL":
			out.ImageURL = string(in.String())
		case "Content":
			out.Content = string(in.String())
		case "Link":
			out.Link = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar11(out *jwriter.Writer, in CommunityEngagementHelper) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Width\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Width))
	}
	{
		const prefix string = ",\"Title\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"ImageURL\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ImageURL))
	}
	{
		const prefix string = ",\"Content\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Content))
	}
	{
		const prefix string = ",\"Link\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Link))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CommunityEngagementHelper) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CommunityEngagementHelper) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CommunityEngagementHelper) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CommunityEngagementHelper) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar11(l, v)
}
func easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar12(in *jlexer.Lexer, out *BulletHelper) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Bullet1":
			out.Bullet1 = string(in.String())
		case "Bullet2":
			out.Bullet2 = string(in.String())
		case "Bullet3":
			out.Bullet3 = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar12(out *jwriter.Writer, in BulletHelper) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Bullet1\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Bullet1))
	}
	{
		const prefix string = ",\"Bullet2\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Bullet2))
	}
	{
		const prefix string = ",\"Bullet3\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Bullet3))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BulletHelper) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BulletHelper) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BulletHelper) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BulletHelper) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar12(l, v)
}
func easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar13(in *jlexer.Lexer, out *ArchitectureHelper) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "SpaceLayoutImage":
			out.SpaceLayoutImage = string(in.String())
		case "SolarOutputImage":
			out.SolarOutputImage = string(in.String())
		case "SolarArray":
			out.SolarArray = string(in.String())
		case "DailyAvgGeneration":
			out.DailyAvgGeneration = string(in.String())
		case "System":
			out.System = string(in.String())
		case "InverterSize":
			out.InverterSize = string(in.String())
		case "DesignDescription":
			out.DesignDescription = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar13(out *jwriter.Writer, in ArchitectureHelper) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"SpaceLayoutImage\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.SpaceLayoutImage))
	}
	{
		const prefix string = ",\"SolarOutputImage\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.SolarOutputImage))
	}
	{
		const prefix string = ",\"SolarArray\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.SolarArray))
	}
	{
		const prefix string = ",\"DailyAvgGeneration\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.DailyAvgGeneration))
	}
	{
		const prefix string = ",\"System\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.System))
	}
	{
		const prefix string = ",\"InverterSize\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.InverterSize))
	}
	{
		const prefix string = ",\"DesignDescription\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.DesignDescription))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ArchitectureHelper) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ArchitectureHelper) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4a457b9dEncodeGithubComYaleOpenLabOpenxPlatformsOpensolar13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ArchitectureHelper) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ArchitectureHelper) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4a457b9dDecodeGithubComYaleOpenLabOpenxPlatformsOpensolar13(l, v)
}
